'use client'
///Not sure if this should be a client component

import {useState} from 'react'
import DashContainer from "./components/dashboard/DashContainer";
import SideNav from "./components/navigation/SideNav";
import "./globals.css";


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  setNavTab:React.Dispatch<React.SetStateAction<number>>;
}) {

  const [navTab, setNavTab] = useState(0);

  console.log(navTab);
  return (
    <html lang="en">
      <body>
        <SideNav navTab={navTab} setNavTab={setNavTab} />
        <DashContainer children={children} navTab={navTab}/>
      </body>
    </html>
  );
}
