"use client";
///Not sure if this should be a client component

import { useState, useContext, createContext } from "react";
import DashContainer from "./components/dashboard/DashContainer";
import SideNav from "./components/navigation/SideNav";
import "./globals.css";
import { Poppins } from "next/font/google";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

const CaseContext = createContext([]);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  setNavTab: React.Dispatch<React.SetStateAction<number>>;
}) {
  const [navTab, setNavTab] = useState(0);
  const [cases, setCases] = useState([]);

  console.log(navTab);
  return (
    <CaseContext.Provider value={cases}>
      <html lang="en">
        <body className={poppins.className}>
          <SideNav navTab={navTab} setNavTab={setNavTab} />
          <DashContainer children={children} navTab={navTab} />
        </body>
      </html>
    </CaseContext.Provider>
  );
}
